In [ ]:
import numpy as np
from scipy import stats
scipy.stats.mode(arr2)
## mean sabhi ka average 
## MEDIAN MIDDLE wala 
## mode sabse jyada repeat wala


ModuleNotFoundError: No module named 'scipy'

In [2]:
import numpy as np
arr = np.array([1,3,5,6,7])
print(arr)

[1 3 5 6 7]


In [1]:
import numpy as np
x1d= np.array([1,3,4,5])
print(x1d)

[1 3 4 5]


In [2]:
l = [3,4,5,6]
l*2

[3, 4, 5, 6, 3, 4, 5, 6]

In [3]:
x1d*8

array([ 8, 24, 32, 40])

In [4]:
np.array([2,4,6,8,9,0])

array([2, 4, 6, 8, 9, 0])

In [7]:
x=np.array([2,4,6,8,9,0])
x

array([2, 4, 6, 8, 9, 0])

In [8]:
x2d= np.array([[1,3,4,4],[9,8,2,3]])
x2d

array([[1, 3, 4, 4],
       [9, 8, 2, 3]])

In [9]:

x3d=np.array([[[2,3,4,7],[6,7,7,0],[3,4,4,6]]])

In [10]:
x3d

array([[[2, 3, 4, 7],
        [6, 7, 7, 0],
        [3, 4, 4, 6]]])

In [11]:
x3d.shape

(1, 3, 4)

In [13]:
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr=np.array([[2,3,4,5],[3,4,9,0]],ndmin=5)

In [27]:
arr

array([[[[[2, 3, 4, 5],
          [3, 4, 9, 0]]]]])

In [29]:
type(arr)
print(arr.ndim)

5


In [30]:

arr=np.array([[2,3,4,5],[3,4,9,0]],dtype='int32')

In [31]:
arr

array([[2, 3, 4, 5],
       [3, 4, 9, 0]], dtype=int32)

In [32]:
arr.ndim

2

In [33]:
arr.shape

(2, 4)

In [34]:
arr.size

8

In [35]:
arr.dtype

dtype('int32')

In [44]:
x = np.array([2,4,5,6])
x.reshape(2,2)

array([[2, 4],
       [5, 6]])

In [47]:
x.T

array([2, 4, 5, 6])

In [48]:
x_2d=np.array([[3,4],[6,7]])

In [50]:
x_2d

array([[3, 4],
       [6, 7]])

In [52]:
x_2d.T

array([[3, 6],
       [4, 7]])

In [55]:
e=np.arange(12)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
e.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
for i in e:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [60]:
for i in e:
    print(i,end=",")

0,1,2,3,4,5,6,7,8,9,10,11,

In [61]:

w=np.array([[3,4],[5,6],[7,8]])

In [62]:
for i in np.nditer(w):
    print(i)

3
4
5
6
7
8


In [4]:
import numpy as np

In [6]:
x3d=np.array([[[2,3,4,7],[6,7,7,0],[3,4,4,6]]])
x3d.shape

(1, 3, 4)

In [8]:
l1=[2,3,5]
a1=np.array(l1)
l2=[5,6,9]
a2=np.array(l2)
print(l1+l2)
print(a1+a2)

[2, 3, 5, 5, 6, 9]
[ 7  9 14]


In [3]:
import numpy as np

In [6]:
# Remove outliers
data = np.array([1, 2, 3, 100, 2, 3])
cleaned = data[(data > 0) & (data < 10)]

In [7]:
cleaned

array([1, 2, 3, 2, 3])

In [8]:
data

array([  1,   2,   3, 100,   2,   3])

In [10]:
scores = np.array([85, 92, 88, 79, 95])
top_3 = np.sort(scores)[-3:]# [88, 92, 95]


In [11]:
scores

array([85, 92, 88, 79, 95])

In [12]:
top_3

array([88, 92, 95])

In [ ]:
mask = np.array([True, False, True, False, True])
filtered = arr[mask]# [10, 30, 50]

NameError: name 'array' is not defined

In [20]:
arr_2d = np.array([[3, 1], [5, 2], [4, 0]])

# Sort each row
 = np.sort(arr_2d, axis=1)

# Sort each column
col_sorted = np.sort(arr_2d, axis=0)

# Sort by specific column (fancy indexing)
sorted_by_col1 = arr_2d[arr_2d[:,1].argsort()]row_sorted

IndentationError: unexpected indent (3595608883.py, line 4)

In [18]:
row_sorted

array([[1, 3],
       [2, 5],
       [0, 4]])

In [19]:
col_sorted

array([[3, 0],
       [4, 1],
       [5, 2]])